callNumberChecker/urls.py
from django.urls import path

from . import views

app_name = 'callNumberChecker'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('output', views.OutputView.as_view(), name='output'),
    path('reset', views.ResetView.as_view(), name="reset")
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('callNumberChecker/', include('callNumberChecker.urls')),
    path('admin/', admin.site.urls),
]

callNumberChecker/models.py
from django.db import models

class RecordID(models.Model):
  record_id = models.CharField(max_length=13, default='0000000', editable=False)
  cTop = models.CharField(max_length=10, default='0000000', editable=False)
  cMdl = models.CharField(max_length=10, default='0000000', editable=False)
  cBtm = models.CharField(max_length=10, default='0000000', editable=False)
  is_right_callNumber = models.BooleanField(default=True)

  def __str__(self):
        return self.record_id

callNumberChecker/forms.py
from django import forms
import unicodedata
import re

from .models import RecordID
from .scraping import scraping

class ContactForm(forms.Form):
  record_id = forms.CharField(label="資料ID")

  def clean(self):
    cleaned_data = super().clean()
    text = cleaned_data.get("record_id")

    if isEmpty(text):
      raise forms.ValidationError("13桁の半角数字を入力してください。")
    
    elif len(text) != 13 or isHalfNum(text) != True:
      raise forms.ValidationError("13桁の半角数字を入力してください。")

    if RecordID.objects.filter(record_id=text):
      raise forms.ValidationError("資料ID:{}は登録済みです。".format(text))

    info = scraping(text)
    if info["is_right_id"] != True:
      raise forms.ValidationError("資料ID:{}は存在しません。".format(text))
    
    cleaned_data["cTop"] = info["cTop"]
    cleaned_data["cMdl"] = info["cMdl"]
    cleaned_data["cBtm"] = info["cBtm"]
    
    return cleaned_data

  def save(self):
    data = self.cleaned_data
    recordid = RecordID(
      record_id = data["record_id"],
      cTop = data["cTop"],
      cMdl = data["cMdl"],
      cBtm = data["cBtm"],
      is_right_callNumber = isRightCallNumber(data["cTop"], data["cMdl"], data["cBtm"])
      )
    recordid.save()

def isHalfNum(str):
    try:
      int(str)
    except ValueError:
      return False
    for char in str:
      if 'Na' != unicodedata.east_asian_width(char):
        return False
    return True

def isEmpty(str):
  try:
    len(str)
  except TypeError:
    return True
  return False

def isRightCallNumber(cTop, cMdl, cBtm):
  d = {'　': ''}
  tbl = str.maketrans(d)
  ctop = cTop.translate(tbl)
  cmdl = cMdl.translate(tbl)

  if len(ctop) > 0 and len(cmdl) > 0:
    p = re.compile('[a-zA-Z]+')
    rectop = "".join(re.findall(p,ctop))
    recmdl = "".join(re.findall(p,cmdl))

    if rectop == ctop or recmdl == cmdl:
      p = re.compile('[0-9.]+')
      rectop = "".join(re.findall(p,ctop))
      recmdl = "".join(re.findall(p,cmdl))
      if rectop == ctop or recmdl == cmdl:
        return True
  return False

callNumberChecker/views.py
# from django import forms
from django.views.generic.edit import FormView
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponse
from django import forms
from django.shortcuts import redirect

from .forms import ContactForm
from .models import RecordID

class IndexView(FormView):
    form_class = ContactForm
    template_name = 'callNumberChecker/index.html'
    success_url = reverse_lazy('callNumberChecker:index')
    model = RecordID

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        recordid = RecordID.objects.all()
        kwargs['recordid'] = recordid
        kwargs['len_of_recordid'] = len(recordid)
        if len(recordid):
            kwargs['last_callNumber_is_right'] = recordid[len(recordid)-1].is_right_callNumber == True
            kwargs['last_callNumber_is_wrong'] = recordid[len(recordid)-1].is_right_callNumber == False
        else: kwargs['last_callNumber_is_right'] = kwargs['last_callNumber_is_wrong'] = False

        kwargs['right_count'] = len(list(filter(
            lambda x: x.is_right_callNumber == True, recordid)))
        kwargs['wrong_count'] = len(list(filter(
            lambda x: x.is_right_callNumber == False, recordid)))
        context = super().get_context_data(**kwargs)
        return context

class OutputView(generic.DetailView):

    def dispatch(self, *args, **kwargs):
        response = HttpResponse(content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=背ラベル出力.txt'
        # Designate The Model
        recordid = RecordID.objects.filter(is_right_callNumber = True)

        # Create blank list
        lines = []
        # Loop Thu and output
        for id in recordid:
            lines.append('{}\n'.format(id.record_id))
        response.writelines(lines)
        return response

class ResetView(generic.DetailView):

    def dispatch(self, *args, **kwargs):
        RecordID.objects.all().delete()
        response = redirect('callNumberChecker:index')
        return response

callNumberChecker/templates/callNumberChecker/base.html
<!doctype HTML>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      </head>
    <body>
      <header>
      <nav class="navbar navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'callNumberChecker:index' %}">請求記号検査システム</a>
      </nav>
      </header>
      <main role="main" class="p-3">
        <div class="container-fluid">
          {% block main %}
          <p>※コンテンツがありません。</p>
          {% endblock %}
        </div>
      </main>
    </body>
</html>

callNumberChecker/templates/callNumberChecker/index.html
{% extends "callNumberChecker/base.html" %}
{% block main %}
<div class="row">
  {% for error in form.non_field_errors %}
  <div class="col-12">
    <div class="alert alert-danger">
      {{ error }}
    </div>
  </div>
  {% endfor %}
</div>
<div class="row">
  <div class="col-12">
    <form method="post" name="research">
      <fieldset>
        {% csrf_token %}
        <p>
          <label for="record_id">資料ID</label>
          <input type="text" name="record_id" id="record_id">
          <input type="button" value="検索" name="research" class="btn btn-info" onclick="rset(this.form);">
        </p>
        <script type="text/javascript">
          function rset(f){
            f.submit();
            f.reset();
          }
        </script>
        <script type="text/javascript">
        window.onload = function() {
          document.getElementById('record_id').focus();
        };
        </script>
      </fieldset>
    </form>
    </div>
</div>
<div class="row">
  <div class="col-6">
    {% if right_count != 0 %}
    <a href="{% url 'callNumberChecker:output' %}" class="btn btn-info">ファイル出力</a>
    {% endif %}
  </div>
  <div class="col-6">
    {% if len_of_recordid != 0 %}
    <form method="get" name="delete">
      {% csrf_token %}
      <p>
        <a href="{% url 'callNumberChecker:reset' %}" class="btn btn-info">リセット</a>
      </p>
    </form>
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-6">
    {% if last_callNumber_is_right %}
    <u><h5>正しい・・・{{ right_count }}件</h5></u>
    {% else %}
    <h5>正しい・・・{{ right_count }}件</h5>
    {% endif %}
    <ul>
      {% for id in recordid %}
      {% if id.is_right_callNumber %}
        <li>
          <div class="row">
            <div class="col-4">
              {{ id.record_id }}
            </div>
            <div class="col-8">
              {{id.cTop}} || {{id.cMdl}} || {{id.cBtm}}
            </div>
          </div>
        </li>
      {% endif %}
      {% endfor %}
    </ul>
  </div>
  <div class="col-6">
    {% if last_callNumber_is_wrong %}
    <u><h5>誤り・・・{{ wrong_count }}件</h5></u>
    {% else %}
    <h5>誤り・・・{{ wrong_count }}件</h5>
    {% endif %}
      <ul>
        {% for id in recordid %}
        {% if not id.is_right_callNumber %}
        <li>
          <div class="row">
            <div class="col-4">
              {{ id.record_id }}
            </div>
            <div class="col-8">
              {{id.cTop}} || {{id.cMdl}} || {{id.cBtm}}
            </div>
          </div>
        </li>
        {% endif %}
        {% endfor %}
      </ul>
  </div>
</div>
{% endblock %}